### PR TITLE
Ensure directive works when image src changes

### PR DESCRIPTION
**Pull request by lookitsatravis**
Hello!

First, thanks for the great project!

My use cause which caused me issues is that I'm using a cropping tool to generate a data URL and using the data URL with ng-src on my image element. On first load, ng-image-appear worked as expected, but whenever ng-src changed and the load event was triggered again on the image element, ng-image-appear tries to remove a loader that no longer exists. This is a simple fix to make sure the loader element exists before trying to remove it.

Thanks!

### CODE REVIEW

**Comment by lookitsatravis** [comment]
I'm actually going to add to this PR. I found another issue after further usage related to changing ng-src with ng-image-loader. Essentially, the image wrapper element is removed on load (right after the loader). When the image src changes `loadImage` is called which calls `removeImgWrapper`, and the issue happens at [Line 183](https://github.com/ArunMichaelDsouza/ng-image-appear/blob/master/src/js/ng-image-appear.js#L183) where the parent node and grand parent nodes are manipulated. The issue is that there is no longer an image wrapper after the first load.

I think the solution to this is to watch for src changes, and re-init the directive so that each source change behaves as if it were the first. I'll put some more work into this tonight and update this PR.

**Comment by lookitsatravis** [comment]
Alright, I think this is ready for review now. Basically, I wrapped the setup code into an `initialize` method, and I added a watcher for the image element's src. If it changes, the directive treats it as if it loaded for the first time. The end result is that it should work identically for an `img` element using `src`, and it should also accommodate using `ng-src` directive to programmatically set the source of the image.

**Comment by ArunMichaelDsouza** [comment]
Hey @lookitsatravis. Thanks a lot for the PR! This was indeed a necessary fix. I had to do minor fixes to it, in order to make it work dynamically with ng-src. It works fine and has been merged.

**Comment by lookitsatravis** [comment]
@ArunMichaelDsouza no worries! This library is great, and I really appreciate you putting it out there. Hey, one thing I just noticed, though, is that it looks like you made some changes on master for fallback image support like in 054e62f41f333e49fbfeb8234a489a6208ee577a. I didn't merge any of those changes from master into my PR (I just saw them) and it looks like they got nuked during the merge. Just wanted to point it out to you in case you didn't already know.

**Comment by ArunMichaelDsouza** [comment]
Ya I know, that was intentional. It was just a random test. Will continue it in a separate branch. I am planning to add built in fallback support for broken image links, will probably release it in some time. 
If you come across any other issue or have a feature in mind do send a PR.

Thanks again for contributing. Cheers!

**Pull request merged**
